apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: builtin-prom-mgo
  namespace: demo
spec:
  version: "4.1"
  terminationPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/builtin
